### PR TITLE
FST reader update to support new Kaldi versions

### PR DESCRIPTION
**Pull request by mdoulaty**
https://groups.google.com/d/msg/kaldi-help/0SuCkeHyUmU/SogcAuWbBQAJ
New Kaldi versions have an updated FST reader

### CODE REVIEW

**Comment by mdoulaty** [comment]
this should solve https://github.com/dialogflow/asr-server/issues/34

**Comment by realill** [comment]
Does it still work with older FST format? Like this one https://github.com/dialogflow/api-ai-english-asr-model ?

**Comment by mdoulaty** [comment]
yes, it does

**Comment by mdoulaty** [comment]
the pre-trained models that you mentioned (https://github.com/dialogflow/api-ai-english-asr-model), works as expected after this change

**Comment by realill** [comment]
Merged. Thanks.

**Pull request merged**
